services:
  - type: web
    name: elegant-progressive-ladies
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn simple_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 