services:
  - type: web
    name: elegant-progressive-ladies
    env: python
    buildCommand: pip install -r requirements.txt && pip install Flask-Login==0.5.0
    startCommand: gunicorn simple_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 
      - key: FLASK_APP
        value: simple_app.py
      - key: FLASK_ENV
        value: production 